name: SM First GitHub Action

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Chekcout code
        uses: actions/checkout@v3

      - name: Say hello
        run: |
          echo "안녕하세요! 첫번째 GitHub Action 입니다,"
          echo "현재 시간: $(date)"
          echo "실행된 브랜치: ${{ github.ref}}"

      - name: Show environment
        run: |
        echo "운영체제: ${{ runner.os }}"
        echo "저장소: ${{ github.repository}}"
